#!/bin/zsh

chosen=$(echo "Log Out\nReboot\nPower Off" | rofi -dmenu -i -p "⏻ " -theme-str 'entry {enabled: false;} window {width: 15%;}' -l 3 -location 0 -yoffset -150 -no-show-icons)

case $chosen in
    "Log Out")
        herbstclient quit
        ;;
    "Reboot")
        reboot
        ;;
    "Power Off")
        poweroff
        ;;
esac

